language: "en"
first_run: true

reanimation:
  require_special_item: true
  required_item: GOLDEN_APPLE
  duration_ticks: 100
  health_restored: 4
  cooldown: 60
  revive_cooldown: 60

knockout:
  enabled: true
  duration_seconds: 30
  movement_disabled: true
  use_particles: true
  heartbeat_sound: true
  blindness: true
  suicide_hold_seconds: 3

execution:
  enabled: true
  hold_duration_ticks: 40
  message_broadcast: true

effects_on_revive:
  nausea: 5
  slowness: 10
  resistance: 10

prone:
  enabled: true
  allow_crawl: true
  crawl_slowness_level: 5
  auto_crawl: false

looting:
  enabled: true

tablist:
  enabled: true
